### ISSUE TITLE
RuntimeError: Unknown model (vit_base_resnet50_384)

### ISSUE THREAD

**Issue by Iliceth** [TrickyGo/Pano2Room#3]
When running the test `sh scripts/run_Pano2Room.sh`, I end up with this error:

```
Detectron v2 is not installed
/home/user/miniconda3/envs/pano2room/lib/python3.10/site-packages/torch/utils/_contextlib.py:125: UserWarning: Decorating classes is deprecated and will be disabled in future versions. You should only decorate functions or methods. To preserve the current behavior of class decoration, you can directly decorate the `__init__` method and nothing else.
  warnings.warn("Decorating classes is deprecated and will be disabled in "
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00,  6.65it/s]
Traceback (most recent call last):
  File "/home/user/Documents/pano2room/pano2room.py", line 605, in <module>
    pipeline = Pano2RoomPipeline()
  File "/home/user/miniconda3/envs/pano2room/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/miniconda3/envs/pano2room/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 129, in <lambda>
    func = cast(F, lambda *args, **kwargs: orig_func(*args, **kwargs))
  File "/home/user/Documents/pano2room/pano2room.py", line 81, in __init__
    self.load_modules()
  File "/home/user/Documents/pano2room/pano2room.py", line 85, in load_modules
    self.geo_predictor = PanoJointPredictor(save_path=self.save_path)
  File "/home/user/Documents/pano2room/modules/geo_predictors/pano_joint_predictor.py", line 78, in __init__
    self.depth_predictor = OmnidataPredictor()
  File "/home/user/Documents/pano2room/modules/geo_predictors/omnidata/omnidata_predictor.py", line 39, in __init__
    self.model = DPTDepthModel(backbone='vitb_rn50_384', num_channels=1)
  File "/home/user/Documents/pano2room/modules/geo_predictors/omnidata/modules/midas/dpt_depth.py", line 101, in __init__
    super().__init__(head, **kwargs)
  File "/home/user/Documents/pano2room/modules/geo_predictors/omnidata/modules/midas/dpt_depth.py", line 48, in __init__
    self.pretrained, self.scratch = _make_encoder(
  File "/home/user/Documents/pano2room/modules/geo_predictors/omnidata/modules/midas/blocks.py", line 20, in _make_encoder
    pretrained = _make_pretrained_vitb_rn50_384(
  File "/home/user/Documents/pano2room/modules/geo_predictors/omnidata/modules/midas/vit.py", line 483, in _make_pretrained_vitb_rn50_384
    model = timm.create_model("vit_base_resnet50_384", pretrained=pretrained)
  File "/home/user/miniconda3/envs/pano2room/lib/python3.10/site-packages/timm/models/_factory.py", line 89, in create_model
    raise RuntimeError('Unknown model (%s)' % model_name)
RuntimeError: Unknown model (vit_base_resnet50_384)

```

The 3 checkpoints are present as instructed.

**Comment by Iliceth** [comment]
I had to reinstall timm via 

`pip install git+https://github.com/rwightman/pytorch-image-models.git `

instead of via the requirements.txt / pip package, although the same (!) version number, that helped the code to continue.

**Comment by Iliceth** [comment]
The process now gets to the intended output, so that's great. :-)

Although, I wanted to know if any of the warnings I get, can be resolved and/or are not an issue:

```
Detectron v2 is not installed

/home/user/miniconda3/envs/pano2room/lib/python3.10/site-packages/torch/utils/_contextlib.py:125: UserWarning: Decorating classes is deprecated and will be disabled in future versions. You should only decorate functions or methods. To preserve the current behavior of class decoration, you can directly decorate the `__init__` method and nothing else.
  warnings.warn("Decorating classes is deprecated and will be disabled in "

/home/user/miniconda3/envs/pano2room/lib/python3.10/site-packages/timm/models/_factory.py:117: UserWarning: Mapping deprecated model name vit_base_resnet50_384 to current vit_base_r50_s16_384.orig_in21k_ft_in1k.
  model = create_fn(

/home/user/miniconda3/envs/pano2room/lib/python3.10/site-packages/torch/nn/functional.py:4236: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(

/home/user/miniconda3/envs/pano2room/lib/python3.10/site-packages/torchvision/transforms/functional.py:1603: UserWarning: The default value of the antialias parameter of all the resizing transforms (Resize(), RandomResizedCrop(), etc.) will change from None to True in v0.17, in order to be consistent across the PIL and Tensor backends. To suppress this warning, directly pass antialias=True (recommended, future default), antialias=None (current default, which means False for Tensors and True for PIL), or antialias=False (only works on Tensors - PIL will still use antialiasing). This also applies if you are using the inference transforms from the models weights: update the call to weights.transforms(antialias=True).
  warnings.warn(

/home/user/miniconda3/envs/pano2room/lib/python3.10/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]

/home/user/Documents/pano2room/utils/functions.py:82: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:206.)
  return torch.Tensor(np.asarray(pil)).permute(2,0,1).unsqueeze(0).float()/255 #BCHW
```
